import type { Metadata } from 'next'
import { Ubuntu } from 'next/font/google'
import './globals.css'

import Header from './components/Header'
import Head from './head'

const ubuntu = Ubuntu({
  weight: "400",
  subsets: ['latin'],
  preload: true
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-br">
      <Head />
      <body className={ubuntu.className}>
        <Header />
        {children}
      </body>
    </html>
  )
}
